spring:
  application:
    name: advanced-database
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ecommerce}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
